version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stw0rd
      POSTGRES_DB: jobs
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: p4ssw0rd
      MONGO_INITDB_DATABASE: quotes
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
      - ./mongo/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 5s
      timeout: 1m
      retries: 10
      start_period: 5s
  mongo-express:
    image: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: p4ssw0rd
      ME_CONFIG_MONGODB_URL: mongodb://admin:p4ssw0rd@mongo:27017/
  quotes-api:
    build: quotes-api
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 8080:8080

volumes:
  postgres:
  mongo:
