spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: quotes
            username: quotes_user
            password: quotes_password
            auto-index-creation: true

springdoc:
    swagger-ui:
        path: /swagger-ui
